### ISSUE TITLE
can not install on Ubuntu 12.04

### ISSUE THREAD

**Issue by serefarikan** [thk686/rpg#1]
all attempts to install under Ubuntu 12.04 fails with the following error:
- installing _source_ package ‘rpg’ ...
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking target system type... x86_64-unknown-linux-gnu
  checking for pg_config... no
  configure: checking for PostgreSQL header files
  configure: Checking include /usr/include.
  configure: Checking include /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include.
  configure: Checking include /usr/include/pgsql.
  configure: Checking include /usr/include/postgresql.
  configure: Checking include /usr/local/include.
  configure: Checking include /usr/local/include/pgsql.
  configure: Checking include /usr/local/include/postgresql.
  configure: Checking include /usr/local/pgsql/include.
  configure: Checking include /usr/local/postgresql/include.
  configure: Checking include /opt/include.
  configure: Checking include /opt/include/pgsql.
  configure: Checking include /opt/include/postgresql.
  configure: Checking include /opt/local/include.
  configure: Checking include /opt/local/include/postgresql.
  configure: Checking include /opt/local/include/postgresql84.
  configure: Checking include /sw/opt/postgresql-8.4/include.
  configure: Checking include /Library/PostgresPlus/8.4SS/include.
  configure: Checking include /sw/include/postgresql.
  configure: Checking lib /usr/lib.
  configure: Checking lib /usr/lib/pgsql.
  configure: Checking lib /usr/lib/postgresql.
  configure: Checking lib /usr/local/lib.
  configure: Checking lib /usr/local/lib/pgsql.
  configure: Checking lib /usr/local/lib/postgresql.
  configure: Checking lib /usr/local/pgsql/lib.
  configure: Checking lib /usr/local/postgresql/lib.
  configure: Checking lib /opt/lib.
  configure: Checking lib /opt/lib/pgsql.
  configure: Checking lib /opt/lib/postgresql.
  configure: Checking lib /opt/local/lib.
  configure: Checking lib /opt/local/lib/postgresql.
  configure: Checking lib /opt/local/lib/postgresql84.
  configure: Checking lib /sw/opt/postgresql-8.4/lib.
  configure: Checking lib /Library/PostgresPlus/8.4SS/lib.
  configure: Checking lib /sw/lib.
  checking for "/libpq-fe.h"... no
  configure: creating ./config.status
  config.status: creating src/Makevars
  *\* libs
  g++ -I/usr/share/R/include -DNDEBUG -I  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/RApiSerialize/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
  RcppExports.cpp:4:18: fatal error: Rcpp.h: No such file or directory
  compilation terminated.
  make: **\* [RcppExports.o] Error 1
  ERROR: compilation failed for package ‘rpg’
- removing ‘/usr/local/lib/R/site-library/rpg’

The downloaded source packages are in
        ‘/tmp/RtmppivKyx/downloaded_packages’
Warning message:
In install.packages("rpg", repos = "http://R-Forge.R-project.org") :
  installation of package ‘rpg’ had non-zero exit status

This is from an R session run with sudo R. Running R as a normal user does not make a difference. 
devtools, rcpp and roxygen2 installs complete successfully without any issues. 

I'm using this package under Windows and tried to move my code over to linux, then discovered this error.

**Comment by serefarikan** [comment]
OK, I figured it out. even though the error complains about Rcpp.h, the problem is libpq-dev. When I install this library, the installation works. The installation notes on the main page claim the sources would pull this library automatically but apparently that is not happening.

**Comment by thk686** [comment]
Can you send the Makevars file in src from the failed build? Also, the
build setup is copied from the RPostgreSQL package. Can you try installing
that in the environment where rpg failed? Thanks.

THK

On Fri, Mar 20, 2015 at 1:54 PM, serefarikan notifications@github.com
wrote:

> OK, I figured it out. even though the error complains about Rcpp.h, the
> problem is libpq-dev. When I install this library, the installation works.
> The installation notes on the main page claim the sources would pull this
> library automatically but apparently that is not happening.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/thk686/rpg/issues/1#issuecomment-84099648.

## 

http://www.keittlab.org/

**Comment by thk686** [comment]
No reproducible example. I am closing.
