### ISSUE TITLE
Allow append option in write_table

### ISSUE THREAD

**Issue by verajosemanuel** [thk686/rpg#5]
would be very useful to allow append data to an existing table.

Thanks for such an excellent package

**Comment by thk686** [comment]
Do you mean in the write_table function?

THK

http://www.keittlab.org/

**Comment by verajosemanuel** [comment]
yep, allowing to add data instead of overwriting, 
RPostgresql and RPostgres packages got an option called     append = TRUE/FALSE

thanks

**Comment by thk686** [comment]
That's easy to add. In the mean-time, 'copy_to' does append and is vastly
faster (but does require psql in your path).

THK

**Comment by thk686** [comment]
Added in 1.6
