### ISSUE TITLE
Fetch column names for any result

### ISSUE THREAD

**Issue by struckma** [thk686/rpg#6]
Dear Tim,

thank you for your gread PostgreSQL driver. I use it frequently for work now and you did a great job. I have only one small wish and would be glad, if you could consider it.

For queries returning at least one row, the column names are returned as column names of the returned data frame. For various reasons (logging, returning empty but named data frames as described in https://stackoverflow.com/a/19931164) it wouuld be reasonable to access the column names in any case, so I would really appreciate, if you could consider adding rpg:::get_tuple_info() to the public API and place it in the exports in NAMESPACE.

Thank you again,

Stephan

**Comment by thk686** [comment]
I exported get_tuple_info in 1.6. Is there perhaps though a better way to accomplish what you are trying to do?

**Comment by struckma** [comment]
Dear Tim,

thank you very much. Regarding you concern: Sure, it would be possible to access the postgres-scheme and query it for available columns, but this would be inventing the wheel twice. 

I need it for an extension, I could contribute, because I consider it less straight-forward regarding the data.frame-interface to return `NULL `for an empty data set compared to return an empty data frame. This would be _more intuitive_ and lead to cleaner code:
  * _no case decision_ would be necessary, loops over an empty frame would work simply work as expected
  * _column.names would always be available,_ not only if data is returned. In fact, that's where I need it internally currently.

I know, this cannot be easily changed, since the API would change, so I would introduce a new function `fetch_df` which would always return a (possibly empty) data.frame with all columns in.

I don't know, if you like this idea, and there are certainly also good reasons for returning `NULL`, but if you like, I could add this function and create a pull-request thereafter; but I'm also fine with it, if you don't like.

Thank you any way for your support and the great package. Best wishes,

Stephan

**Comment by thk686** [comment]
I need a working example of code that returns NULL instead of an empty data
frame.

THK

**Comment by thk686** [comment]
It was a trivial one-line fix. It will now return a data frame with zero rows if the query does not contain any rows.

**Comment by struckma** [comment]
Thank you, this is great!
