### ISSUE TITLE
.onLoad triggers connect / connect is buggy

### ISSUE THREAD

**Issue by struckma** [thk686/rpg#7]
Dear Tim,

it's me again. Sorry, but I have another bug and a feature-request: On Windows, there is no passwordless authentication for a user database by default. Nevertheless, if I load rpg on a Windows PC, already the .onLoad function triggers a connect call. This call then fails, and as long as the R shell is `interactive()`, the system asks for a password. Besides this should be optional and maybe only triggered by `.onAttach`, not `.onLoad` (feature request part), the password thereafter is handled wrong by the `connect `routine (I translated the error message, maybe the exact error message may differ):
```
> rpg::connect()
Error: .onLoad in loadNamespace() for 'rpg' failed, details:
  Call: connect()
  Error: object 'keywords' not found
```

This error stems from https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L96 where keywords is extended by the entered password. `dbname` was missing (`.onLoad` called `connect()`). Therefore https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L82 is executed, where then `values `become a zero-length  #list; so for the `if` statement in https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L85 its related else-block in https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L87 followed by https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L88 is never reached and `keywords` is never defined. Later in https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L96 the extension of `keywords` must fail.

I propose to

  * remove the `connect()` call from `.onLoad` (and only maybe put it into `.onAttach`, if you really need this), because there may not even be any database to connect when only the package is loaded -- currently loading fails, if no passwordless authentication is possible.
  * amend https://github.com/thk686/rpg/blob/8425255edccf82612e0b40e7954a4b1803f90a19/R/rpg.R#L86 by defining `keywords = c(); connect_(character(0), character(0))`, so that `keywords` are always defined, because then the interactively reasd password would really be used and not trigger an error any more, if `connect()` is called w/o any parameters.

I hope, that I am not too annoying, being still very impressed by your prompt responses. Thank you very much again,

Stephan

**Comment by thk686** [comment]
Fixed.

**Comment by struckma** [comment]
Great, Thanks!
